files:
- generatedChecksum: AB67D8A7D0606ADFF3E9184E6CB5B5F9
  logicalPath: config/LED_Driver
  name: exceptions.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: AB67D8A7D0606ADFF3E9184E6CB5B5F9
- generatedChecksum: 35D2CF725E178A98027AE92C0C855FD9
  logicalPath: config/LED_Driver
  name: initialization.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 35D2CF725E178A98027AE92C0C855FD9
- generatedChecksum: 65ED0CF2427B1E8AB4156513B8CC4937
  logicalPath: config/LED_Driver
  name: interrupts.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 65ED0CF2427B1E8AB4156513B8CC4937
- generatedChecksum: null
  logicalPath: ''
  name: main.c
  physicalPath: ../..
  security: NON_SECURE
  type: SOURCE
  userChecksum: null
- generatedChecksum: FB3D52F6B1C45EB5471D8A54163393E0
  logicalPath: config/LED_Driver/peripheral/clk
  name: plib_clk.c
  physicalPath: peripheral/clk
  security: NON_SECURE
  type: SOURCE
  userChecksum: FB3D52F6B1C45EB5471D8A54163393E0
- generatedChecksum: DF796FCA118C8FB86E2DBE4474FC6CD8
  logicalPath: config/LED_Driver/peripheral/evic
  name: plib_evic.c
  physicalPath: peripheral/evic
  security: NON_SECURE
  type: SOURCE
  userChecksum: DF796FCA118C8FB86E2DBE4474FC6CD8
- generatedChecksum: 5280A21F3116E2BAA4E41651E8554637
  logicalPath: config/LED_Driver/peripheral/gpio
  name: plib_gpio.c
  physicalPath: peripheral/gpio
  security: NON_SECURE
  type: SOURCE
  userChecksum: 5280A21F3116E2BAA4E41651E8554637
- generatedChecksum: ABA1DB8EC565E27B9EB7C715092B1EFA
  logicalPath: config/LED_Driver/peripheral/tmr
  name: plib_tmr2.c
  physicalPath: peripheral/tmr
  security: NON_SECURE
  type: SOURCE
  userChecksum: ABA1DB8EC565E27B9EB7C715092B1EFA
- generatedChecksum: 145BC516E950A7FEA233D3341A07F65D
  logicalPath: config/LED_Driver/peripheral/uart
  name: plib_uart6.c
  physicalPath: peripheral/uart
  security: NON_SECURE
  type: SOURCE
  userChecksum: 145BC516E950A7FEA233D3341A07F65D
- generatedChecksum: 71352EF41F6688AD8408E42970B50B66
  logicalPath: config/LED_Driver/stdio
  name: xc32_monitor.c
  physicalPath: stdio
  security: NON_SECURE
  type: SOURCE
  userChecksum: 71352EF41F6688AD8408E42970B50B66
- generatedChecksum: 93EACDC43B0FFBDAB266D948E5726751
  logicalPath: config/LED_Driver
  name: definitions.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 93EACDC43B0FFBDAB266D948E5726751
- generatedChecksum: E189C26B2269F8DE46033CCD0621958D
  logicalPath: config/LED_Driver
  name: device.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: E189C26B2269F8DE46033CCD0621958D
- generatedChecksum: 4CF4A86296482D5331331BA301C20BB2
  logicalPath: config/LED_Driver
  name: interrupts.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 4CF4A86296482D5331331BA301C20BB2
- generatedChecksum: 7066CC390335CF75126E2A50C46E3BDD
  logicalPath: config/LED_Driver/peripheral/clk
  name: plib_clk.h
  physicalPath: peripheral/clk
  security: NON_SECURE
  type: HEADER
  userChecksum: 7066CC390335CF75126E2A50C46E3BDD
- generatedChecksum: 815CCB981B6CB758464D89480121DC08
  logicalPath: config/LED_Driver/peripheral/evic
  name: plib_evic.h
  physicalPath: peripheral/evic
  security: NON_SECURE
  type: HEADER
  userChecksum: 815CCB981B6CB758464D89480121DC08
- generatedChecksum: 1040EB93F8BC95D243B14FD4A95C6D57
  logicalPath: config/LED_Driver/peripheral/gpio
  name: plib_gpio.h
  physicalPath: peripheral/gpio
  security: NON_SECURE
  type: HEADER
  userChecksum: 1040EB93F8BC95D243B14FD4A95C6D57
- generatedChecksum: 612994C7F3C27F2CFA2621C1F65D4068
  logicalPath: config/LED_Driver/peripheral/tmr
  name: plib_tmr2.h
  physicalPath: peripheral/tmr
  security: NON_SECURE
  type: HEADER
  userChecksum: 612994C7F3C27F2CFA2621C1F65D4068
- generatedChecksum: D948F2CE092CAB556EF299D3CCD83A55
  logicalPath: config/LED_Driver/peripheral/tmr
  name: plib_tmr_common.h
  physicalPath: peripheral/tmr
  security: NON_SECURE
  type: HEADER
  userChecksum: D948F2CE092CAB556EF299D3CCD83A55
- generatedChecksum: CE96102E92CBCE4BCED61DBB8932DC25
  logicalPath: config/LED_Driver/peripheral/uart
  name: plib_uart6.h
  physicalPath: peripheral/uart
  security: NON_SECURE
  type: HEADER
  userChecksum: CE96102E92CBCE4BCED61DBB8932DC25
- generatedChecksum: 91611515A95D92B82B7F4064C16D122B
  logicalPath: config/LED_Driver/peripheral/uart
  name: plib_uart_common.h
  physicalPath: peripheral/uart
  security: NON_SECURE
  type: HEADER
  userChecksum: 91611515A95D92B82B7F4064C16D122B
- generatedChecksum: CAC44960D20AEC03CF4B325A1CD2877C
  logicalPath: config/LED_Driver
  name: toolchain_specifics.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: CAC44960D20AEC03CF4B325A1CD2877C
- generatedChecksum: 07A482DAB7473FC475EA656561967B15
  logicalPath: config/LED_Driver
  name: p32MZ2048EFM144.ld
  physicalPath: ''
  security: NON_SECURE
  type: LINKER
  userChecksum: 07A482DAB7473FC475EA656561967B15
format_version: v1.0
libraries: []
settings:
- append: true
  category: C32
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/LED_Driver;
- append: false
  category: C32
  delimiter: ''
  key: generate-micro-compressed-code
  security: NON_SECURE
  value: 'false'
- append: false
  category: C32-LD
  delimiter: ''
  key: heap-size
  security: NON_SECURE
  value: '512'
- append: false
  category: C32-LD
  delimiter: ''
  key: no-device-startup-code
  security: NON_SECURE
  value: 'true'
- append: true
  category: C32-LD
  delimiter: ;=
  key: preprocessor-macros
  security: NON_SECURE
  value: ''
- append: true
  category: C32CPP
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/LED_Driver;
- append: false
  category: C32CPP
  delimiter: ''
  key: generate-micro-compressed-code
  security: NON_SECURE
  value: 'false'
sourcePaths: []
