configName: LED_Driver
folderName: LED_Driver
format_version: v1.0
frameworkPath: ../../Harmony3
processor: PIC32MZ2048EFM144
projectName: LED_Driver
settings:
  PackageFilter: bsp;quick_docs;harmony-services;reference_apps;crypto;usb;dev_packs;core_apps_pic32mz_ef;core;csp
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: ./dev_packs/arm/CMSIS/5.8.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: ./dev_packs/Microchip/PIC32MZ-EF_DFP/1.3.58/atdf/PIC32MZ2048EFM144.atdf
